// Generated by CoffeeScript 1.6.3
(function() {
  var Client, Status, WebSocketServer, action, clients, config, getClientByName, getLobbyNames, lobby, sendLobbyUpdate, wss;

  config = require("./config.json");

  action = require("./action.json");

  WebSocketServer = require('ws').Server;

  wss = new WebSocketServer({
    port: config.port
  });

  clients = [];

  lobby = [];

  getLobbyNames = function() {
    var client, _i, _len, _results;
    _results = [];
    for (_i = 0, _len = lobby.length; _i < _len; _i++) {
      client = lobby[_i];
      _results.push(client.name);
    }
    return _results;
  };

  sendLobbyUpdate = function() {
    var client, names, _i, _len, _results;
    names = getLobbyNames();
    _results = [];
    for (_i = 0, _len = lobby.length; _i < _len; _i++) {
      client = lobby[_i];
      _results.push(client.connection.send(JSON.stringify({
        action: action.server.lobbyUpdate,
        names: names
      })));
    }
    return _results;
  };

  getClientByName = function(name) {
    var client, _i, _len;
    for (_i = 0, _len = lobby.length; _i < _len; _i++) {
      client = lobby[_i];
      if (name === client.name) {
        return client;
      }
    }
  };

  Status = {
    unidentified: function(data) {
      console.log(data.action);
      switch (data.action) {
        case action.client.setName:
          this.name = data.value;
          this.status = Status.nowhere;
          this.connection.send(JSON.stringify({
            action: "confirm",
            name: this.name
          }));
          return console.log("A client set its name to " + this.name);
        default:
          return Status.error("unidentified", data);
      }
    },
    nowhere: function(data) {
      switch (data.action) {
        case action.client.goToLobby:
          console.log("" + this.name + " goes to the lobby");
          lobby.push(this);
          this.status = Status.lobby;
          console.log("" + lobby.length + " clients are in the lobby");
          return sendLobbyUpdate();
        default:
          return Status.error("nowhere", data);
      }
    },
    lobby: function(data) {
      switch (data.action) {
        case action.client.pair:
          console.log("" + this.name + " wants to pair with " + data.partner);
          this.partner = getClientByName(data.partner);
          this.partner.partner = this;
          lobby.splice(lobby.indexOf(this, 1));
          lobby.splice(lobby.indexOf(this.partner, 1));
          return this.partner.connection.send(JSON.stringify({
            action: action.server.request,
            partner: this.name
          }));
        case action.client.accept:
          console.log("" + this.partner.name + " has accepted");
          this.partner.connection.send(JSON.stringify({
            action: action.server.start
          }));
          this.status = Status.ingame;
          return this.partner.status = Status.ingame;
        case action.client.deny:
          console.log("" + this.partner.name + " has denied");
          this.partner.connection.send(JSON.stringify({
            action: action.server.denied
          }));
          lobby.push(this);
          lobby.push(this.partner);
          this.partner.partner = void 0;
          this.partner = void 0;
          return sendLobbyUpdate();
        default:
          return Status.error("lobby", data);
      }
    },
    ingame: function(data) {
      switch (data.action) {
        case action.client.turn:
          console.log("" + this.name + " has made his turn");
          return this.partner.connection.send(JSON.stringify({
            action: action.server.turn,
            value: data.value
          }));
        default:
          return Status.error("ingame", data);
      }
    },
    error: function(status, data) {
      return console.log("Client has the status " + status + ". It can not receive the action " + data.action);
    }
  };

  Client = function(connection) {
    var _this = this;
    this.connection = connection;
    this.partner = void 0;
    this.name = void 0;
    this.status = Status.unidentified;
    this.connection.on('close', function() {
      if (_this.status === Status.ingame) {
        _this.partner.connection.send("partner disconnected");
      }
      console.log("" + _this.name + " disconnected");
      lobby.splice(lobby.indexOf(_this), 1);
      clients.splice(clients.indexOf(_this), 1);
      return console.log("Now there are " + clients.length + " clients online.");
    });
    return this.connection.on('message', function(message) {
      var data, e;
      try {
        data = JSON.parse(message);
        if (data != null ? data.action : void 0) {
          return _this.status(data);
        }
      } catch (_error) {
        e = _error;
        return console.log("Error parsing " + message + ": " + e);
      }
    });
  };

  wss.on("connection", function(ws) {
    console.log("A client connected.");
    clients.push(new Client(ws));
    return console.log("Now there are " + clients.length + " clients online.");
  });

}).call(this);
